### ISSUE TITLE
ActiveModel::UnknownAttributeError (unknown attribute 'dim' for Unitize::MeasurementUnit.)

### ISSUE THREAD

**Issue by i2chris** [pinkynrg/Unitize#2]
I get the above error message when running this code:

```
f_unit = Unitize::MeasurementUnit.create({
	name: "meter", 
	measurement_type: m_type, 
	code: "m", 
	symbol: "m", 
	dim: "M"
})
```
Thanks

**Comment by pinkynrg** [comment]
That probably is more a mistake in the documentation. I did adapt another gem (Unitwise) to work on a database for my own needs. That was a column that I probably removed since it was useless to me. 

Try removing the dim parameter and it should work. 

Parameters in MeasurementUnit model are:

name, measurement_type, code, scale_value, scale_unit_code, classification, metric, base, symbol, scale_function_from and scale_function_to

**Comment by pinkynrg** [comment]
confirm that the dim is an old attribute. Will correct the README.md.

closing.
